### ISSUE TITLE
2nd measure unable to product white text

### ISSUE THREAD

**Issue by edwardlayys** [ChristofSchwarz/qs_ext_rag_select#1]
Hello Chrisof,

Love your extension, however, I do have an issue here. When I put in more than 90 buttons, the text colour of each button does not change to the intended colour (for example, 'white'). Could you help me to check on this?

**Comment by ChristofSchwarz** [comment]
Can you export and share the app where you have this issue? Either upload here or send to christof.schwarz@gmx.at

**Comment by edwardlayys** [comment]
hello Christof, thanks for the reply. I tried in a sample app and the white text colour works. Tried it back on the actual app that I had trouble with, i restarted every steps for this extension and seems like it works. 

Not sure what happens, cant replicate the steps to produce the error. You may close this issue.
